### ISSUE TITLE
if save_model is passed through the fit_opts = {} in tune() it is not being actioned on

### ISSUE THREAD

**Issue by ayn2** [tsrobinson/SyGNet#33]
tune(
    my_dict,
    train_data,
    runs=4,
    model_opts = {'mixed_activation': 'False'},
    fit_opts = {'save_model': 'False'},
    test_opts = {'some_arg': 'some_value'},
    mode = "wgan",
    k = 5,
    tuner = "random",
    epochs = 2,
    seed = 89,
    device = 'cpu')

gets an error

File "C:\Users\Artem\PythonProjects\Public_SyGNet\src\sygnet\interface.py", line 277, in fit
    with open(filepath / (save_prefix + datetime.now().strftime("%d%b%y_%H%M")), 'wb') as f:
UnboundLocalError: local variable 'filepath' referenced before assignment

despite that we asked not to save the model.

p.s. It actually triggers a logger message Argument `save_loc` must contain a directory path...

**Comment by tsrobinson** [comment]
Thanks @ayn2, keep me posted on your progress here. As a starter for ten, I would try removing the quotes around False in the argument of `fit_opts`.

**Comment by ayn2** [comment]
If False passed without commas, it works. closed.
